version: "3"
services:
   mymongo:
     image: mongo:latest
     container_name: "mymongo"
     ports:
       - 27017:27017
   docker-spingboot:
      image: docker-springboot
      container_name: docker-springboot
      ports:
        - 8083:8083
      links:
        - mymongo

